name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to live branch
      if: success()
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b live
        git add -A
        git commit -m "Deploy to live"
        git push -f origin live