name: test build and deploy to live

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: install dependencies
      run: |
        gem install bundler
        bundle install

    - name: test build site
      run: bundle exec jekyll build

    - name: deploy to live branch
      if: success()
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch origin live:live
        git checkout live
        git merge main
        COMMIT_MSG=$(git log -1 --pretty=%B)
        git commit --amend -m "deploy to live: $COMMIT_MSG"
        git push -f origin live
        git checkout main